import { CarVehicleMakeEnum } from '../enums/car-vehicle-make.enum';

export const carModelsByMake: Record<CarVehicleMakeEnum, string[]> = {
  [CarVehicleMakeEnum.BMW]: [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'Z4',
    'M2',
    'M3',
    'M4',
    'M5',
    'M8',
    'i3',
    'i4',
    'i7',
    'iX',
    'iX3',
  ],
  [CarVehicleMakeEnum.Audi]: [
    'A1',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q2',
    'Q3',
    'Q4 e-tron',
    'Q5',
    'Q7',
    'Q8',
    'TT',
    'R8',
    'RS3',
    'RS4',
    'RS5',
    'RS6',
    'RS7',
    'e-tron GT',
    'S3',
    'S4',
    'S5',
    'S6',
    'S7',
    'S8',
  ],
  [CarVehicleMakeEnum.MercedesBenz]: [
    'A-Class',
    'B-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'CLA',
    'CLS',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'G-Class',
    'SL',
    'AMG GT',
    'EQC',
    'EQA',
    'EQB',
    'EQE',
    'EQS',
    'SLC',
    'V-Class',
  ],
  [CarVehicleMakeEnum.Toyota]: [
    'Corolla',
    'Camry',
    'Prius',
    'Yaris',
    'Avalon',
    'RAV4',
    'Highlander',
    'Land Cruiser',
    'Tacoma',
    'Tundra',
    'C-HR',
    '4Runner',
    'Supra',
    'GR86',
    'Mirai',
  ],
  [CarVehicleMakeEnum.Honda]: [
    'Civic',
    'Accord',
    'Fit',
    'Insight',
    'CR-V',
    'HR-V',
    'Pilot',
    'Passport',
    'Odyssey',
    'Ridgeline',
    'Prelude',
    'S2000',
  ],
  [CarVehicleMakeEnum.Ford]: [
    'Fiesta',
    'Focus',
    'Fusion',
    'Mustang',
    'Escape',
    'Edge',
    'Explorer',
    'Expedition',
    'Ranger',
    'F-150',
    'Bronco',
    'Maverick',
  ],
  [CarVehicleMakeEnum.Chevrolet]: [
    'Spark',
    'Malibu',
    'Impala',
    'Camaro',
    'Corvette',
    'Trailblazer',
    'Equinox',
    'Traverse',
    'Tahoe',
    'Suburban',
    'Silverado',
    'Colorado',
    'Blazer',
  ],
  [CarVehicleMakeEnum.Tesla]: [
    'Model S',
    'Model 3',
    'Model X',
    'Model Y',
    'Cybertruck',
    'Roadster',
  ],
  [CarVehicleMakeEnum.Nissan]: [
    'Micra',
    'Versa',
    'Sentra',
    'Altima',
    'Maxima',
    'Leaf',
    '370Z',
    'GT-R',
    'Kicks',
    'Rogue',
    'Murano',
    'Pathfinder',
    'Armada',
    'Titan',
  ],
  [CarVehicleMakeEnum.Hyundai]: [
    'Accent',
    'Elantra',
    'Sonata',
    'Ioniq',
    'Kona',
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Veloster',
    'Nexo',
  ],
  [CarVehicleMakeEnum.Kia]: [
    'Rio',
    'Forte',
    'Optima',
    'Stinger',
    'Seltos',
    'Sportage',
    'Sorento',
    'Telluride',
    'Soul',
    'Niro',
    'EV6',
  ],
  [CarVehicleMakeEnum.Volkswagen]: [
    '181',
    'Amarok',
    'Anfibio',
    'Arteon',
    'Atlas',
    'Beetle',
    'Bora',
    'Buggy',
    'Bus',
    'Caddy',
    'CC',
    'Coccinelle',
    'Corrado',
    'Crafter',
    'Cross Touran',
    'Derby',
    'e-up!',
    'Eos',
    'Escarabajo',
    'Fox',
    'Golf',
    'Cross Golf',
    'e-Golf',
    'Golf Cabriolet',
    'Golf GTD',
    'Golf GTE',
    'Golf GTI',
    'Golf Plus',
    'Golf R',
    'Golf Sportsvan',
    'Golf Variant',
    'Grand California',
    'ID. Buzz',
    'ID.3',
    'ID.4',
    'ID.5',
    'ID.6',
    'ID.7',
    'Iltis',
    'Jetta',
    'Kafer',
    'Karmann Ghia',
    'Kever',
    'L80',
    'LT',
    'Lupo',
    'Maggiolino',
    'New Beetle',
    'Passat',
    'Passat Altrack',
    'Passat CC',
    'Passat Variant',
    'Phaeton',
    'Pointer',
    'Polo',
    'Polo Cross',
    'Polo Plus',
    'Polo R WRC',
    'Polo Sedan',
    'Polo Variant',
    'Routan',
    'Santana',
    'Scirocco',
    'Sharan',
    'T-Cross',
    'T-Roc',
    'T1',
    'T2',
    'T3',
    'T5',
    'T6',
    'T6.1',
    'T7',
    'Taigo',
    'Taro',
    'Tayron',
    'Tiguan',
    'Touareg',
    'Touran',
    'Transporter',
    'up!',
    'Vento',
    'Viloran',
    'XL1',
  ],
  [CarVehicleMakeEnum.Subaru]: [
    'Impreza',
    'Legacy',
    'Outback',
    'Forester',
    'Crosstrek',
    'Ascent',
    'BRZ',
    'WRX',
  ],
  [CarVehicleMakeEnum.Volvo]: [
    'XC40',
    'XC60',
    'XC90',
    'S60',
    'S90',
    'V60',
    'V90',
  ],
  [CarVehicleMakeEnum.Jaguar]: [
    'XE',
    'XF',
    'XJ',
    'F-Type',
    'E-Pace',
    'F-Pace',
    'I-Pace',
  ],
  [CarVehicleMakeEnum.LandRover]: [
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
    'Discovery',
    'Defender',
  ],
  [CarVehicleMakeEnum.Porsche]: [
    '911',
    '718 Boxster',
    '718 Cayman',
    'Panamera',
    'Macan',
    'Cayenne',
    'Taycan',
  ],
  [CarVehicleMakeEnum.Ferrari]: [
    'Roma',
    'Portofino',
    'F8 Tributo',
    'SF90 Stradale',
    '812 Superfast',
    '296 GTB',
    'Purosangue',
  ],
  [CarVehicleMakeEnum.Lamborghini]: [
    'Huracan',
    'Aventador',
    'Urus',
    'Revuelto',
  ],
  [CarVehicleMakeEnum.Maserati]: [
    'Ghibli',
    'Quattroporte',
    'Levante',
    'MC20',
    'GranTurismo',
  ],
  [CarVehicleMakeEnum.AstonMartin]: [
    'DB11',
    'DBS',
    'Vantage',
    'DBX',
    'Valhalla',
    'Valkyrie',
  ],
  [CarVehicleMakeEnum.Opel]: [
    'Adam',
    'Agila',
    'Ampera',
    'Ampera-E',
    'Antara',
    'Arena',
    'Ascona',
    'Astra',
    'Calibra',
    'Campo',
    'Cascada',
    'Combo',
    'Combo Life',
    'Combo-e',
    'Combo-e Life',
    'Commodore',
    'Corsa',
    'Corsa-e',
    'Crossland',
    'Crossland X',
    'Diplomat',
    'Frontera',
    'Grandland',
    'Grandland X',
    'GT',
    'Insignia',
    'Kadett',
    'Karl',
    'Manta',
    'Meriva',
    'Mookka',
    'Mookka X',
    'Mookka-E',
    'Monterey',
    'Monza',
    'Movano',
    'Movano-e',
    'Omega',
    'Pick Up Stortscap',
    'Rekord',
    'Rocks-e',
    'Senator',
    'Signum',
    'Sintra',
    'Speedster',
    'Tigra',
    'Vectra',
    'Vivaro',
    'Vivaro-e',
    'Zafira',
    'Zafira Life',
    'Zafira Tourer',
  ],
  [CarVehicleMakeEnum.Renault]: [
    'Alaskan',
    'Alphine A100',
    'Alphine A310',
    'Alphine A610',
    'Alphine V6',
    'Arkana',
    'Austral',
    'Avantime',
    'Captur',
    'Clio',
    'Coupe',
    'Duster',
    'Espace',
    'Express',
    'Fluence',
    'Fluence Z.E.',
    'Fuego',
    'Grand Espace',
    'Crand Modus',
    'Grand Scenic',
    'Kadjar',
    'Kangoo',
    'Kangoo E-TECH',
    'Kangoo Z.E.',
    'Koleos',
    'Laguna',
    'Latitude',
    'Logan',
    'Mascott',
    'Master',
    'Megane',
    'Megane E-Tech',
    'Messenger',
    'Modus',
    'Rafale',
    'Rapid',
    'Safrane',
    'Sandero',
    'Sandero Stepway',
    'Scenic',
    'Spider',
    'Super 5',
    'Symbioz',
    'Symbol',
    'Talisman',
    'Traffic',
    'Twingo',
    'Twizy',
    'Vel Satis',
    'Wind',
    'ZOE',
  ],
  [CarVehicleMakeEnum.Acura] : [
    'ILX',
    'MDX',
    'NSX',
    'RDX',
    'RL',
    'RLX',
    'RSX',
    'TL',
    'TLX',
    'TSX',
    'ZDX',
  ],
  [CarVehicleMakeEnum.AlfaRomeo]: [
    '145',
    '146',
    '147',
    '155',
    '156',
    '159',
    '164',
    '166',
    '1750',
    '2000',
    '33',
    '4C',
    '75',
    '8C',
    '90',
    'Alfa 6',
    'Alfasud',
    'Alfetta',
    'Brera',
    'Crosswagon',
    'Giulia',
    'Giulietta',
    'GT',
    'GTV',
    'Junior',
    'MiTo',
    'Montreal',
    'Quadrifoglio',
    'RZ',
    'Spider',
    'Sportwagon',
    'Sprint',
    'Stelvio',
    'SZ',
    'Tonale',
  ],
  [CarVehicleMakeEnum.Bentley]: [
    'Arnage',
    'Azure',
    'Bacalar',
    'Bentayga',
    'Brooklands',
    'Continental',
    'Continental GT',
    'Continental GTC',
    'Eight',
    'Flying Spur',
    'Mulsanne',
    'S1',
    'S2',
    'S3',
    'Turbo R',
    'Turbo RT',
    'Turbo S',
  ],
};
