export const motorcycleBodyType: { key: string; value: string }[] = [
  { key: 'Supersport', value: 'Supersport' },
  { key: 'Sport touring', value: 'Sport touring' },
  { key: 'Chopper/Cruiser', value: 'Chopper/Cruiser' },
  { key: 'Touring Enduro', value: 'Touring Enduro' },
  { key: 'Streetfighter', value: 'Streetfighter' },
  { key: 'Enduro bike', value: 'Enduro bike' },
  { key: 'Motocrosser', value: 'Motocrosser' },
  { key: 'Sidecar', value: 'Sidecar' },
  { key: 'Classic', value: 'Classic' },
  { key: 'Scooter', value: 'Scooter' },
  { key: 'Moped', value: 'Moped' },
  { key: 'Super Moto', value: 'Super Moto' },
  { key: 'Minibike', value: 'Minibike' },
  { key: 'Others', value: 'Others' },
  { key: 'Naked Bike', value: 'Naked Bike' },
  { key: 'Quad', value: 'Quad' },
  { key: 'Rally', value: 'Rally' },
  { key: 'Trials Bike', value: 'Trials Bike' },
  { key: 'Racing', value: 'Racing' },
  { key: 'Tourer', value: 'Tourer' },
]
